using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;

namespace VCS.Editor
{
    /// <summary>
    /// Applies player settings and creates the few assets the runtime needs (scene, materials).
    /// Runs before every build and is available from the VCS menu.
    /// </summary>
    public static class ProjectSetup
    {
        public const string ScenePath = "Assets/Scenes/Main.unity";

        [MenuItem("VCS/Setup Project")]
        public static void Apply()
        {
            PlayerSettings.productName = "Vacuum Cleaner Simulator 2026";
            PlayerSettings.companyName = "Cosnuau";
            PlayerSettings.bundleVersion = "0.2.0";
            PlayerSettings.colorSpace = ColorSpace.Linear;
            PlayerSettings.fullScreenMode = FullScreenMode.FullScreenWindow;
            PlayerSettings.resizableWindow = true;
            PlayerSettings.runInBackground = true;
            PlayerSettings.defaultIsNativeResolution = true;
            PlayerSettings.SetScriptingBackend(NamedBuildTarget.Standalone, ScriptingImplementation.Mono2x);
            PlayerSettings.SetApiCompatibilityLevel(NamedBuildTarget.Standalone, ApiCompatibilityLevel.NET_Standard);
            // Mono player: no need for UnityLinker stripping, and the linker step is what fails on this machine.
            PlayerSettings.SetManagedStrippingLevel(NamedBuildTarget.Standalone, ManagedStrippingLevel.Disabled);
            EnsureMaterials();
            EnsurePostProcessResources();
            EnsureScene();
            ApplyIcon();
            AssetDatabase.SaveAssets();
            Debug.Log("[VCS] Project setup applied.");
        }

        // The app icon lives at Assets/Icon/icon.png (generated by the marketing campaign). Optional.
        static void ApplyIcon()
        {
            const string path = "Assets/Icon/icon.png";
            var tex = AssetDatabase.LoadAssetAtPath<Texture2D>(path);
            if (tex == null) return;
            var importer = AssetImporter.GetAtPath(path) as TextureImporter;
            if (importer != null && (importer.textureType != TextureImporterType.Default || !importer.isReadable))
            {
                importer.textureType = TextureImporterType.Default;
                importer.isReadable = true;
                importer.mipmapEnabled = false;
                importer.SaveAndReimport();
                tex = AssetDatabase.LoadAssetAtPath<Texture2D>(path);
            }
            var target = NamedBuildTarget.Standalone;
            var sizes = PlayerSettings.GetIconSizes(target, IconKind.Any);
            var icons = new Texture2D[sizes.Length];
            for (int i = 0; i < icons.Length; i++) icons[i] = tex;
            PlayerSettings.SetIcons(target, icons, IconKind.Any);
            var defaults = PlayerSettings.GetIconSizes(NamedBuildTarget.Unknown, IconKind.Any);
            var defaultIcons = new Texture2D[defaults.Length];
            for (int i = 0; i < defaultIcons.Length; i++) defaultIcons[i] = tex;
            PlayerSettings.SetIcons(NamedBuildTarget.Unknown, defaultIcons, IconKind.Any);
            Debug.Log("[VCS] Icon applied from " + path);
        }

        // Post Processing v2 finds its shaders through this asset; copying it under Resources puts it (and the
        // shaders it references) in the build so RenderingSetup can load it at runtime.
        static void EnsurePostProcessResources()
        {
            const string src = "Packages/com.unity.postprocessing/PostProcessing/PostProcessResources.asset";
            const string dst = "Assets/Resources/PostProcessResources.asset";
            if (AssetDatabase.LoadAssetAtPath<Object>(dst) != null) return;
            if (AssetDatabase.LoadAssetAtPath<Object>(src) == null) { Debug.LogWarning("[VCS] Post-processing package not resolved yet: " + src); return; }
            Directory.CreateDirectory("Assets/Resources");
            if (AssetDatabase.CopyAsset(src, dst)) Debug.Log("[VCS] PostProcessResources copied to Resources");
            else Debug.LogWarning("[VCS] Could not copy PostProcessResources");
        }

        static void EnsureMaterials()
        {
            Directory.CreateDirectory("Assets/Resources/Materials");
            EnsureMaterial("Assets/Resources/Materials/Lit.mat", "Standard", m =>
            {
                m.SetFloat("_Glossiness", 0.25f);
                m.SetFloat("_Metallic", 0f);
            });
            EnsureMaterial("Assets/Resources/Materials/Particle.mat", "Legacy Shaders/Particles/Alpha Blended", m =>
            {
                m.SetColor("_TintColor", new Color(0.5f, 0.5f, 0.5f, 0.5f));
            });
            // Standard in Fade mode (the powder layers): the keyword must live in an asset or the variant is stripped.
            EnsureMaterial("Assets/Resources/Materials/Fade.mat", "Standard", m =>
            {
                m.SetFloat("_Mode", 2f);
                m.SetOverrideTag("RenderType", "Transparent");
                m.SetInt("_SrcBlend", (int)UnityEngine.Rendering.BlendMode.SrcAlpha);
                m.SetInt("_DstBlend", (int)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
                m.SetInt("_ZWrite", 0);
                m.DisableKeyword("_ALPHATEST_ON");
                m.EnableKeyword("_ALPHABLEND_ON");
                m.DisableKeyword("_ALPHAPREMULTIPLY_ON");
                m.renderQueue = 3000;
                m.SetFloat("_Glossiness", 0.05f);
                m.SetFloat("_Metallic", 0f);
            });
            // Standard with emission (LEDs and displays): same reason.
            EnsureMaterial("Assets/Resources/Materials/LitEmissive.mat", "Standard", m =>
            {
                m.EnableKeyword("_EMISSION");
                m.SetColor("_EmissionColor", Color.white);
                m.globalIlluminationFlags = MaterialGlobalIlluminationFlags.RealtimeEmissive;
                m.SetFloat("_Glossiness", 0.7f);
                m.SetFloat("_Metallic", 0f);
            });
            // Standard with a normal map (every plastic, rubber, fabric and metal): same reason.
            EnsureMaterial("Assets/Resources/Materials/LitBump.mat", "Standard", m =>
            {
                m.EnableKeyword("_NORMALMAP");
                m.SetFloat("_BumpScale", 0.5f);
                m.SetFloat("_Glossiness", 0.5f);
                m.SetFloat("_Metallic", 0f);
            });
        }

        static void EnsureMaterial(string path, string shaderName, System.Action<Material> configure)
        {
            if (AssetDatabase.LoadAssetAtPath<Material>(path) != null) return;
            var shader = Shader.Find(shaderName);
            if (shader == null)
            {
                Debug.LogWarning("[VCS] Shader not found: " + shaderName);
                return;
            }
            var m = new Material(shader);
            configure(m);
            AssetDatabase.CreateAsset(m, path);
            Debug.Log("[VCS] Created " + path);
        }

        static void EnsureScene()
        {
            if (!File.Exists(ScenePath))
            {
                Directory.CreateDirectory("Assets/Scenes");
                var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
                EditorSceneManager.SaveScene(scene, ScenePath);
                Debug.Log("[VCS] Created " + ScenePath);
            }
            EditorBuildSettings.scenes = new[] { new EditorBuildSettingsScene(ScenePath, true) };
        }
    }
}
